name: Build and Release DEB Package
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Build DEB package
      run: ./gradlew buildDeb
    - name: Extract version from yaml
      id: version
      run: | 
         echo "version=$(grep 'versionName' gradle/libs.versions.toml | cut -d '"' -f 2)" >> $GITHUB_OUTPUT
         echo "Version: $VERSION"
    - name: Determine tag name
      id: tag_name
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "TAG_NAME=v${{ steps.get_version.outputs.VERSION }}" >> $GITHUB_OUTPUT
        fi
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_name.outputs.TAG_NAME }}
        name: mjdev server v${{ steps.get_version.outputs.VERSION }}
        body: |
          ## mjdev server release v${{ steps.get_version.outputs.VERSION }}
          ### Changes
          - Automated release with DEB package
          ### Installation
          Download the `mjdev-server.deb` file and install it using:
          ```bash
          sudo dpkg -i mjdev-server.deb
          sudo apt-get install -f  # Fix any dependency issues
          ```
          ### What's included
          - complete mjdev server project tree
          - installation scripts
          - automatic dependency installation via postinst script
        files: |
          ./release/mjdev-server*.deb
        draft: false
        prerelease: false
